language: go

go:
- 1.8

script: make release

deploy:
  provider: releases
  api_key:
    secure: "a6tPl+E1ZUobxKMV3jJkKcN2xlGmF6feTWlk/+aSkH/LEDLx675Y0EtNPFMxhs7EB0Tzl+uqVrlYw3y5UL3MLhEyW+3pj7Pxs0a970n2xy0jINWT/Gtkc8sItydoqdsvTf7ZFR50pHYwlwubkuxmsbE09sZfRttkXdVWCIUu4n708T1ZK8vXuVNDt+Z1KhKSY6zSXYxM/HkURRAVfqc6RiXXXgEKyVJMmzUXysaC+/s8V9o2F9JmbIyG7RY3ovPT77CwE6U6ozMcpoLUkt32OXVm0o0POfpA3FGOxIcrxpkqMuxExMilTS0DVxJTWnzkk2uFDt6H+EKqIRIauXmhiDi/mRTyxBk9IEFhoUa0bc6hbiZ1BrmVmFT9Tsi90JmKJexRlsgkjHIAxn3BWSeSH4xLN5ySZR9xCwnGd+Ja27RK5ui5PJrXKj5+5AEGGiw3UzVeCVcxhohbEnB6ChfC4x2JIq7MzjXPCS7ofNL+Z8CKHoDI4OF1do/RtUlW/sEPkdoe3VAZ3uDnhuYD9+k3naY2JXSLAUxlrYKXrxsgiSJHU/CHcaoFKFNNhBWtweM11oGgMSL8kael2eZcGibZb7UVXrhzfDl2TJGvsgnl7gGck39wxJ+RRPcfOFgCMNpF8SxP2NuWgjRXZV7d5Yi1V/gOIvSwvQCFMfr3kSnDmO8="
  file_glob: true
  file: releases/*
  skip_cleanup: true
  on:
    tags: true
