language: go


go:
  - 1.9

before_install:
  - sudo apt-get update
  - sudo apt-get install ruby ruby-dev
  - ruby -v
  - sudo gem install fpm
  - sudo apt-get install rpm

script:
  - make release

deploy:
  provider: releases
  api_key:
    secure: "karotqZHX5HzqLeJxpnCeDsRun8qdEUeWhc8v1Hr68Ym8K4SXV93LGpWZoQ90ubqS6f84EyL08Y3yydkSWfeKCbeKzoPr/FYnyWaSLZLPUnPWz1Pyqqgyts7qP+Np68ztxyN2ZqB4YrIn/3sUknPZsMz57oxmkrJDUe12T01MLFueOKptmSvN8WyaTutOFNBCGgku2CMraA7NwO+SxeO7HuWXlapPd0qQt1MY+vXNwFStczYWf7lHKQOhzlAGMh/likKky4jR3m+GOmWmY9DHYhjBtLmhU3+a77OfiNPJ0BgvPrMl+7yWonrE8NZt5HgKkOYpRHlMaRIX0Av9MkWrr1vseH1yLGQUaY2HoQdRT0fJb8tdG78w//lwIvZ2wATfhfHjlQalwttfUU3yyJ6Z3hXyvut7rGK9DBfP258dtWaIcyc99Xl+2rr+bbIGrA9i/nS62V0PGs1RKSICVr9BzZBLVp4d1bV5RGk0Ok0/LVvnyLIAgt3OZ/03UPE+/woXJq7zB80D+cOxE0oy01VQ/NQIEkjQ2y93a/eD4sGQd5UeyQlpjBD/ipzml48qqaIqTOhrSOuThVID1P/ajgMwmoqxiGemPV2xzlrbbSS7ImpwwIOgy7q4FAzoEcnYFtE06NYoX2VfYTuL4YJa4SsUYY+JaiEgKL3yD1Ca9nyERs="
  file_glob: true
  file: releases/*
  skip_cleanup: true
  on:
    tags: true
