language: go

go:
- 1.8

script: make release

deploy:
  provider: releases
  api_key:
    secure: EAAHnHDMU9ZYoBuqkjsw1y5n6Dd2QgLMStqcg/OQ4vKe0DeT24e7MVqt4reYHpQETsaLhDpKQasCvDz8Qii/WKnBTihI378bTorNWcmpbXXdDUH80YUVD3f7QGXkTrFpVTNpNUQRLs+Au1N4Mg2Z6zHMEDv6D3qKriwlYQW9mwOLYtwxyGfgS0gESM9uLU7RcqchK2hWZK8r/srB9fihXqPobWVsoMazny5AZ2iKwJUJISF9qxABYic9gEsQ34F8o2KDhc5Ec4eHvic3Qtv4d+fKPEDJNaQFwtK7HfVXDgwbmdfaptGFOPSaBzOxHwcy4iscleKCQILnEY5M+xmJPN+DTEKGhayZyXQJtKAGMxKuY9NpjHCwlFwcchmosSWFGHb4QynMbdit4LqmjchyXlVuzCF+mQ972Ipjcx/1MrwMnTozMY1V05K3MPSN7ab1jzMeIttMp4eQFscQZm+fji6C6onvip9kDyGttqZrkwCGuPyzO+vsS8kaOhLUO2Nw0uPWTtgM5zI5QRAjTks3blKnFKhd6cK4G/d2+n4s+76orVw+bC2HnLe8XWwJpR82vHplbJU5W+a92XfTQWmLOsM5VN0Tj4Yja6COBrgVjWjAzNQTpchFEp7i41i96hGBIBbKrCzAr5yyez6ArWSn5OyCkpUocrOOd8gm2i06P08=
  file_glob: true
  file: releases/*
  skip_cleanup: true
  on:
    tags: true
